#!/usr/bin/env ruby

#
# This is a simple script for parsing the serial data stream from a Current Cost metre.
# Run it like this:
# cc < /dev/ttyUSB0
#

require "rexml/document"

puts "started desu~"

# Running mean.
power_total = 0
power_count = 0
tmpr_total = 0
tmpr_count = 0

# Best way to read stdin?
ARGF.each do |line|
#  puts "line: #{line}"
  if line.strip.length > 0
    power = Integer(line[/<ch1><watts>[0]*([^<]*)</, 1])
    tmpr = Float(line[/<tmpr>([^<]*)</, 1])
    
    power_total += power
    power_count += 1
    power_mean = power_total / ( power_count > 0 ? power_count : 1 )
    
    tmpr_total += tmpr
    tmpr_count += 1
    tmpr_mean = tmpr_total / ( tmpr_count > 0 ? tmpr_count : 1 )
    
    puts "power: #{power} W ( #{power_mean} W ) | tmpr: #{tmpr} C ( #{tmpr_mean} C )"
  end
end

